# Generated by Django 4.1.7 on 2023-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_shoe_img_alter_shoe_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='img',
            field=models.ImageField(upload_to='shoe_image'),
        ),
    ]
