# Generated by Django 4.1.7 on 2023-03-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_shoe_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.CharField(default=50, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='img',
            field=models.ImageField(upload_to='shoes_images'),
        ),
    ]
