# Generated by Django 4.1.7 on 2023-03-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_shoe_price_alter_shoe_brand_alter_shoe_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(default='Nike', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.CharField(default='EGP 50', max_length=10),
        ),
    ]
