# Generated by Django 4.1.7 on 2023-03-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_shoe_color_alter_shoe_brand_alter_shoe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='Type',
            field=models.CharField(default='Men', max_length=10),
        ),
    ]
