# Generated by Django 4.1.7 on 2023-03-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_shoe_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(default='EGP 50', max_length=10)),
            ],
        ),
    ]
