# Generated by Django 4.1.7 on 2023-03-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_home_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_item',
            name='img',
            field=models.ImageField(default='../../../shoes_images/17.jpg', upload_to='shoes_images'),
            preserve_default=False,
        ),
    ]
