# Generated by Django 4.1.7 on 2023-03-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_home_item_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_item',
        ),
    ]
