# Generated by Django 4.1.7 on 2023-03-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0012_alter_shoe_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='size',
            new_name='sizes',
        ),
    ]
