# Generated by Django 4.1.7 on 2023-03-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0013_rename_size_shoe_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='sizes',
        ),
    ]
