# Generated by Django 4.1.7 on 2023-03-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0014_remove_shoe_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='sizes',
            field=models.CharField(default='Small, Medium, Large', max_length=50),
        ),
    ]
