# Generated by Django 4.1.7 on 2023-03-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0018_remove_shoe_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='sizes',
            field=models.CharField(default='M', max_length=50),
        ),
    ]
