# Generated by Django 4.1.7 on 2023-03-21 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0021_shoe_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(default='EGP 50', max_length=10)),
                ('sizes', models.CharField(default='42', max_length=50)),
                ('color', models.CharField(default='White', max_length=50)),
                ('img', models.ImageField(upload_to='shoes_images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
