# Generated by Django 4.1.7 on 2023-03-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0022_user_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='sizes',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='user_order',
            old_name='sizes',
            new_name='size',
        ),
    ]
