# Generated by Django 4.1.7 on 2023-03-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0023_rename_sizes_shoe_size_rename_sizes_user_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
    ]
