# Generated by Django 4.1.7 on 2023-03-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0024_remove_shoe_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.CharField(default='40, 41, 42, 43, 44, 45', max_length=50),
        ),
    ]
