# Generated by Django 4.1.7 on 2023-03-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0025_shoe_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Order',
        ),
    ]
