# Generated by Django 4.1.7 on 2023-03-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0028_shoe_color_hexa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='color_hexa',
        ),
    ]
