# Generated by Django 4.1.7 on 2023-03-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0029_remove_shoe_color_hexa'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='color_hexa',
            field=models.CharField(default='#000000', max_length=50),
        ),
    ]
