# Generated by Django 4.1.7 on 2023-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0030_shoe_color_hexa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='order_num',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
