# Generated by Django 4.1.7 on 2023-03-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes", "0030_shoe_color_hexa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoe",
            name="img",
            field=models.ImageField(upload_to="ShoeZone/static/Media"),
        ),
    ]
