# Generated by Django 4.1.7 on 2023-03-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes", "0031_alter_shoe_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="shoe_num",
            field=models.IntegerField(default=0),
        ),
    ]
