# Generated by Django 4.1.7 on 2023-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0031_user_order_order_num_user_order_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default='#000000', max_length=20)),
                ('items', models.CharField(default='', max_length=9000)),
                ('temp', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user_order',
            name='order_num',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
