# Generated by Django 4.1.7 on 2023-04-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0032_orders_alter_user_order_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='temp',
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.CharField(default='', max_length=100),
        ),
    ]
