# Generated by Django 4.1.7 on 2023-04-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0033_remove_orders_temp_alter_orders_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
