# Generated by Django 4.0.6 on 2023-04-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0033_user_order_order_num_user_order_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ordered', models.CharField(default='', max_length=50)),
                ('order_no', models.CharField(default='#000000', max_length=20)),
                ('items', models.TextField(default='', max_length=1000)),
                ('total_price', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
