# Generated by Django 4.1.7 on 2023-04-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0034_alter_orders_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_ordered',
            field=models.CharField(default='', max_length=50),
        ),
    ]
