# Generated by Django 4.0.6 on 2023-04-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0035_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='selected_size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
