# Generated by Django 4.1.7 on 2023-04-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0035_orders_user_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
