# Generated by Django 4.0.6 on 2023-04-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0036_user_order_selected_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.CharField(default='38 - 45', max_length=50),
        ),
    ]
