# Generated by Django 4.1.7 on 2023-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0036_orders_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='selected_size',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.CharField(default='', max_length=20),
        ),
    ]
