# Generated by Django 4.1.7 on 2023-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0037_orders_selected_size_alter_orders_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='selected_size',
        ),
        migrations.AddField(
            model_name='user_order',
            name='selected_size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
